[project]
name = "ica-data"
version = "0.0.1"
description = "Wrapper for ICA data APIs"
url = "https://github.com/SequenceBio/ica-data"
license = "MIT"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages]
find = {}