[tool.poetry]
name = "ica-data"
version = "0.1.2.6"
description = ""
authors = ["mattstenback <mstenback@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
